/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 5.5.5-10.4.10-MariaDB 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `parameter_analisa` (
	`È#` varchar (15),
	`0$` varchar (765),
	`˜$` varchar (105),
	`ð$` varchar (30),
	`H%` varchar (12),
	` %` varchar (105),
	`ø%` tinyint (1),
	`P&` tinyint (1),
	`¸&` tinyint (1),
	` '` tinyint (1),
	`ˆ'` tinyint (1),
	`à'` tinyint (1),
	`H(` tinyint (1),
	`°(` tinyint (1)
); 
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P001','Brix','Brix','%','k09','','1','1','0','0','1','1','0','1');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P002','Polarization','Pol','%','k09','','1','1','0','0','0','1','0','1');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P003','pH','pH','','k02','','1','0','1','1','1','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P004','Total Solid in Juice','Dirt','%','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P005','Phospate Content after dosing','P2O5 aft.','ppm','k06','','1','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P006','Phospate Content before dosing','P2O5 bfr.','ppm','k06','','1','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P007','Reducing Sugar','RS','%','k11','','1','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P008','Moisture Content','Moist.','%','k01','','1','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P009','Preparation Index','PI','%','k09','','1','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P010','Fiber Content','Fiber','%','k03','','1','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P011','Turbidity','Turb.','NTU','k07','','1','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P012','Calcium Oxide Content','CaO','ppm','k06','','1','0','0','0','1','0','1','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P013','Liquid Colour','Colour','IU','k06','','1','1','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P014','Crystal Colour','CT','CT','k05','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P015','Beume','Be','oBe','k11','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P016','Dextrant Content','Dext.','ppm','k06','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P017','Amylum Content','Amylum','ppm','k06','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P018','Grain Size','G-Size','mm','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P019','Mean Aperture','MA','%','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P020','Coefficient of Variation','CV','%','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P021','Sulfur Dioxide content','SO2','ppm','k11','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P022','Condustivity Ash Content','Ash','ppm','k04','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P023','Sucrose Content','Sucrose','%','k11','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P024','Total Sugar as Invest','TSAI','%','k11','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P025','Viscosity','Visc.','cPa','k10','','0','0','0','0','0','0','1','1');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P026','Sand Content','Sand','%','k11','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P027','Temperature','Temp.','oC','k11','','0','0','0','1','1','0','1','1');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P028','Conductivity','Cond.','Ã¦S/cm','k04','','0','0','1','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P029','Sugar Content','Sugar Content','ppm','k06','','0','0','1','1','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P030','Disv. Oxygen as O2','DO','ppm','k08','','0','0','1','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P031','Total Hardness','Hardness','ppm','k11','','0','0','1','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P032','M. Alkalinity','M-Alk','ppm','k11','','0','0','1','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P033','P.  Alkalinity','P-Alk','ppm','k11','','0','0','1','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P034','O. Alkalinity','O-Alk','ppm','k11','','0','0','1','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P035','Silica as SiO?','SiO2','ppm','k06','','0','0','1','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P036','Phosphate as P2O5','P2O5','ppm','k06','','0','0','1','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P037','Sulphite as Na2SO4','Sulfit','ppm','k06','','0','0','1','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P038','Chloride as NaCL','Chloride','ppm','k06','','0','0','1','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P039','Iron as Fe','Iron','ppm','k06','','0','1','1','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P040','Debit','Debit','m3/day','k11','','0','0','0','1','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P041','Chemical Oxigen Demand','COD','ppm','k06','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P042','Biological Oxigen Demand','BOD','ppm','k11','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P043','Total Suspended Solid','TSS','ppm','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P044','Hydrogen Sulfida','H2S','ppm','k06','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P045','Amoniak','NH3','ppm','k06','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P046','Total Coliform','Coliform','APM/100ml','k11','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P047','Minyak Lemak','Minyak Lemak','ppm','k11','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P048','Berat wadah','Berat wadah','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P049','Berat Awal','Berat Awal','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P050','Berat Akhir','Berat Akhir','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P051','Liquid Colour - brix','Brix Colour','%','k09','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P052','Liquid Colour - Absorbance','Abs Colour','Abs','k06','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P053','Preparation Index - Brix1','Bx PI-1','%','k09','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P054','Preparation Index - Brix2','Bx PI-2','%','k09','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P055','Weight of Bag','Wt Bag','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P056','Weight of Sugar + Bag','Wt Bag brutto','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P057','Weight of Pack','Wt Pack','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P058','Weight of Sugar + Pack','Wt Pack Brutto','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P059','Weight of Box','Wt Box','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P060','Weight of Sugar + Box','Wt Box Brutto','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P061','Berat Fraksi 1 Tarra','Fraksi1 Tarra','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P062','Berat Fraksi 2 Tarra','Fraksi2 Tarra','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P063','Berat Fraksi 3 Tarra','Fraksi3 Tarra','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P064','Berat Fraksi 4 Tarra','Fraksi4 Tarra','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P065','Berat Fraksi 5 Tarra','Fraksi5 Tarra','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P066','Berat Fraksi 6 Tarra','Fraksi6 Tarra','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P067','Berat sample','Sample Gsize','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P068','Berat Fraksi 1 Netto','Fraksi1 Net','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P069','Berat Fraksi 2 Netto','Fraksi2 Net','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P070','Berat Fraksi 3 Netto','Fraksi3 Net','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P071','Berat Fraksi 4 Netto','Fraksi4 Net','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P072','Berat Fraksi 5 Netto','Fraksi5 Net','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P073','Berat Fraksi 6 Netto','Fraksi6 Net','kg','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P074','Standard Deviasi Sugar','SD','%','k03','','0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P075','Losses','Losses','%',NULL,NULL,'1','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P076','Beume','Beume','Be',NULL,NULL,'1','0','0','0','0','0','1','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P077','Solid','Solid','%',NULL,NULL,'1','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P078','Pty','Pty','%',NULL,NULL,'0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P079','Time Strike','Time','',NULL,NULL,'0','0','0','0','0','1','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P080','No Strike','Strike','',NULL,NULL,'0','0','0','0','0','1','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P081','Pan Strike','Pan','',NULL,NULL,'0','0','0','0','0','1','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P082','Boiling Time','BT','',NULL,NULL,'0','0','0','0','0','1','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P083','Volume','Vol','',NULL,NULL,'0','0','0','0','0','1','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P084','Centri fugal','C\'fugal','',NULL,NULL,'0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P085','Grader','Grader','',NULL,NULL,'0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P086','Bag','Bag','',NULL,NULL,'0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P087','WR','WR','',NULL,NULL,'0','0','0','0','0','0','1','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P088','OV','OV ','',NULL,NULL,'0','0','0','0','0','0','1','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P089','Temp-In','Temp-in',NULL,NULL,NULL,'0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P090','Temp-Out','Temp-Out',NULL,NULL,NULL,'0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P091','Brix C1','Bx',NULL,NULL,NULL,'0','0','0','0','0','0','0','0');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P092','C-1 SUGAR Brix','C-1-Bx',NULL,NULL,NULL,'0','0','0','0','0','0','0','1');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P093','C-1 SUGAR Pol','C-1-Pol',NULL,NULL,NULL,'0','0','0','0','0','0','0','1');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P094','Final Molases Brix','Fmol-Bx',NULL,NULL,NULL,'0','0','0','0','0','0','0','1');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P095','Final Molases Pol','Fmol-Pol',NULL,NULL,NULL,'0','0','0','0','0','0','0','1');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P096','Temp Fmol oC','Temp-Fmol-oC',NULL,NULL,NULL,'0','0','0','0','0','0','0','1');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P097','Vol FM lpm','Vol-fm',NULL,NULL,NULL,'0','0','0','0','0','0','0','1');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P098','Load Amp','',NULL,NULL,NULL,'0','0','0','0','0','0','0','1');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P099','Dilt Wtr gmp/lpm','',NULL,NULL,NULL,'0','0','0','0','0','0','0','1');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P100','Temp Dilt. Wtr.oC','',NULL,NULL,NULL,'0','0','0','0','0','0','0','1');
insert into `parameter_analisa` (`id_parameter`, `nama_parameter`, `alias`, `satuan`, `id_klp`, `method`, `is_mill`, `is_boiling`, `is_boiler`, `is_water`, `is_evap`, `is_batch`, `is_floculant`, `is_machine`) values('P101','Press','',NULL,NULL,NULL,'0','0','0','0','1','0','0','0');
